/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import main.InitialView;
import fuzzycontrol.Exercise;
import javax.swing.JOptionPane;

/**
 *
 * @author joslu
 */
public class ControlView extends javax.swing.JFrame {
    
    InitialView initialView;
    Exercise exercise;
    int range1[];
    int range2[];
    int range[];

    /**
     * Creates new form ControlView
     * @param initial
     * @param exerc
     */
    public ControlView(InitialView initial, Exercise exerc) {
        this.initialView = initial;
        this.exercise = exerc;
        range1 = exercise.getValue1Range();
        range2 = exercise.getValue2Range();
        range = exercise.getOutputRange();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_lbl = new javax.swing.JLabel();
        back_btn = new javax.swing.JButton();
        input1_lbl = new javax.swing.JLabel();
        inputValue1_txt = new javax.swing.JTextField();
        input2_lbl = new javax.swing.JLabel();
        inputValue2_txt = new javax.swing.JTextField();
        evaluate_btn = new javax.swing.JButton();
        output_lbl = new javax.swing.JLabel();
        outputValue_txt = new javax.swing.JTextField();
        range1_lbl = new javax.swing.JLabel();
        range2_lbl = new javax.swing.JLabel();
        range_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(exercise.getTitle());
        setResizable(false);

        title_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        title_lbl.setText(exercise.getName());

        back_btn.setText("Regresar");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });

        input1_lbl.setText(exercise.getInputName1());

        input2_lbl.setText(exercise.getInputName2());

        evaluate_btn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        evaluate_btn.setText("Evaluar");
        evaluate_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evaluate_btnActionPerformed(evt);
            }
        });

        output_lbl.setText(exercise.getOutputName());

        outputValue_txt.setEditable(false);

        range1_lbl.setText("["+range1[0]+"-"+range1[1]+"]");

        range2_lbl.setText("["+range2[0]+"-"+range2[1]+"]");

        range_lbl.setText("["+range[0]+"-"+range[1]+"]");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title_lbl)
                    .addComponent(evaluate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(input1_lbl))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputValue1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(range1_lbl)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(back_btn))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(outputValue_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(range_lbl))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(output_lbl)))
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(input2_lbl)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(inputValue2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(range2_lbl)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(title_lbl)
                    .addComponent(back_btn))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(input1_lbl)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputValue1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(range1_lbl)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(input2_lbl)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputValue2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(range2_lbl))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(output_lbl)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(outputValue_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(range_lbl))
                        .addContainerGap(40, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(evaluate_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        this.setVisible(false);
        initialView.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed
    
    private void evaluate_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evaluate_btnActionPerformed
        if(inputValue1_txt.getText().isEmpty() && inputValue2_txt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se puede evaluar variables vacias");
            return;
        }
        boolean var1 = false, var2 = false;
        if(range1[0] <= Double.parseDouble(inputValue1_txt.getText()) && Double.parseDouble(inputValue1_txt.getText()) <= range1[1]) {
            var1 = true;
        } else {
            JOptionPane.showMessageDialog(null, "El valor de "+exercise.getInputName1()+" no esta en el rango");
        }
        if(range2[0] <= Double.parseDouble(inputValue2_txt.getText()) && Double.parseDouble(inputValue2_txt.getText()) <= range2[1]) {
            var2 = true;
        } else {
            JOptionPane.showMessageDialog(null, "El valor de "+exercise.getInputName2()+" no esta en el rango");
        }
        if(var1 && var2) {
            exercise.setInputValue1(Double.parseDouble(inputValue1_txt.getText()));
            exercise.setInputValue2(Double.parseDouble(inputValue2_txt.getText()));
            double result = exercise.getOutputValue();
            outputValue_txt.setText(String.valueOf(result));
        }
        
    }//GEN-LAST:event_evaluate_btnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_btn;
    private javax.swing.JButton evaluate_btn;
    private javax.swing.JLabel input1_lbl;
    private javax.swing.JLabel input2_lbl;
    private javax.swing.JTextField inputValue1_txt;
    private javax.swing.JTextField inputValue2_txt;
    private javax.swing.JTextField outputValue_txt;
    private javax.swing.JLabel output_lbl;
    private javax.swing.JLabel range1_lbl;
    private javax.swing.JLabel range2_lbl;
    private javax.swing.JLabel range_lbl;
    private javax.swing.JLabel title_lbl;
    // End of variables declaration//GEN-END:variables
}
